spring:
  application:
    name: ephemeral-secret-vault

  threads:
    virtual:
      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5433/secret_vault_db
    username: vault_user
    password: secret_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

  data:
    redis:
      host: localhost
      port: 6379

springdoc:
  swagger-ui:
    path: /swagger-ui.html